# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'View/MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(540, 660)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.verticalLayout.addWidget(self.line_2)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line_3.sizePolicy().hasHeightForWidth())
        self.line_3.setSizePolicy(sizePolicy)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 4, 0, 1, 4)
        self.dateSelect = QtWidgets.QComboBox(self.centralwidget)
        self.dateSelect.setObjectName("dateSelect")
        self.gridLayout.addWidget(self.dateSelect, 3, 1, 1, 3)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.stockSearchResult = QtWidgets.QLabel(self.centralwidget)
        self.stockSearchResult.setText("")
        self.stockSearchResult.setObjectName("stockSearchResult")
        self.gridLayout.addWidget(self.stockSearchResult, 2, 2, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 1, 1, 1)
        self.searchButton = QtWidgets.QPushButton(self.centralwidget)
        self.searchButton.setObjectName("searchButton")
        self.gridLayout.addWidget(self.searchButton, 1, 3, 1, 1)
        self.recentStocksList = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recentStocksList.sizePolicy().hasHeightForWidth())
        self.recentStocksList.setSizePolicy(sizePolicy)
        self.recentStocksList.setObjectName("recentStocksList")
        self.recentStocksList.addItem("")
        self.recentStocksList.addItem("")
        self.recentStocksList.addItem("")
        self.recentStocksList.addItem("")
        self.recentStocksList.addItem("")
        self.recentStocksList.addItem("")
        self.gridLayout.addWidget(self.recentStocksList, 1, 0, 1, 1)
        self.stockSearchBar = QtWidgets.QLineEdit(self.centralwidget)
        self.stockSearchBar.setObjectName("stockSearchBar")
        self.gridLayout.addWidget(self.stockSearchBar, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_3.addWidget(self.pushButton, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.stockTable = QtWidgets.QTableWidget(self.centralwidget)
        self.stockTable.setObjectName("stockTable")
        self.stockTable.setColumnCount(5)
        self.stockTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.stockTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stockTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stockTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stockTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stockTable.setHorizontalHeaderItem(4, item)
        self.stockTable.horizontalHeader().setStretchLastSection(True)
        self.stockTable.verticalHeader().setSortIndicatorShown(False)
        self.stockTable.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.stockTable)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.exportButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exportButton.sizePolicy().hasHeightForWidth())
        self.exportButton.setSizePolicy(sizePolicy)
        self.exportButton.setObjectName("exportButton")
        self.gridLayout_2.addWidget(self.exportButton, 0, 2, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem2, 0, 1, 1, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 540, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.recentStocksList, self.stockSearchBar)
        MainWindow.setTabOrder(self.stockSearchBar, self.searchButton)
        MainWindow.setTabOrder(self.searchButton, self.stockTable)
        MainWindow.setTabOrder(self.stockTable, self.exportButton)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Select Date:"))
        self.searchButton.setStatusTip(_translate("MainWindow", "Search"))
        self.searchButton.setText(_translate("MainWindow", "Search"))
        self.recentStocksList.setStatusTip(_translate("MainWindow", "Stocks Used in the Last 7 Days"))
        self.recentStocksList.setItemText(0, _translate("MainWindow", "Select Recent"))
        self.recentStocksList.setItemText(1, _translate("MainWindow", " alkdfad"))
        self.recentStocksList.setItemText(2, _translate("MainWindow", "aerwetsg"))
        self.recentStocksList.setItemText(3, _translate("MainWindow", "gjtkut7uryh"))
        self.recentStocksList.setItemText(4, _translate("MainWindow", "24353453rtwrfs"))
        self.recentStocksList.setItemText(5, _translate("MainWindow", "fasdge5j4th3"))
        self.stockSearchBar.setStatusTip(_translate("MainWindow", "Search By Stock Symbol"))
        self.stockSearchBar.setPlaceholderText(_translate("MainWindow", "Stock Symbol Seach"))
        self.label_2.setText(_translate("MainWindow", "Search For Stock Symbol"))
        self.label.setText(_translate("MainWindow", "Recent Stocks List"))
        self.pushButton.setText(_translate("MainWindow", "Import Stock Data"))
        self.stockTable.setStatusTip(_translate("MainWindow", "Imported Stocks Table"))
        self.stockTable.setSortingEnabled(True)
        item = self.stockTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Symbol"))
        item = self.stockTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Current Price"))
        item = self.stockTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "VPM Price"))
        item = self.stockTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "% From Current"))
        item = self.stockTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Date "))
        self.exportButton.setStatusTip(_translate("MainWindow", "Export Stock Table to Excel"))
        self.exportButton.setText(_translate("MainWindow", "Export to Excel"))
        self.pushButton_2.setText(_translate("MainWindow", "Refresh Table"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
